Add check for missing translations
So that we ship all the translations, and don't miss
updating LINGUAS.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -2,3 +2,12 @@ AUTOMAKE_OPTIONS = dist-bzip2
 SUBDIRS = src data tests pam doc po
 EXTRA_DIST = TODO intltool-extract.in intltool-merge.in intltool-update.in
 
+check: check-translations
+
+check-translations:
+	@for i in $(top_srcdir)/po/*.po ; do								\
+		if ! grep -q `basename $$i | sed 's,.po,,'` $(top_srcdir)/po/LINGUAS ; then		\
+			echo '***' `basename $$i | sed 's,.po,,'` missing from po/LINGUAS '***' ;	\
+			exit 1;										\
+		fi;											\
+	done;
